This task will complete task 5 and the respective tests
AndreiThira/andrei-be-nc-news pull request #5
Opened 2023-08-16 09:24 UTC by AndreiThira

2023-08-16 09:42 UTC, mezzDavies requested changes
Good happy path testing 👍  but there is nothing here to test for or handle errors for this endpoint. Please add this sad path and resubmit.  

Also, starting from your next task/branch please name the branches after the task number (this is task 6 not 5 and it's very confusing this side of things 😄 )

(Oh, finally, don't forget to update your endpoints.json!)

2023-08-16 10:51 UTC, poppymcd requested changes
Great work implementing feedback! Only one issue - you should be consistently using either async/await or promises, so make sure your```fetchAllArticles``` and ```fetchCommentsByArticle``` are handled in the same way. Fix that up and resubmit this pull request tomorrow 🙂

2023-08-16 10:51 UTC, poppymcd commented on models/topic-model.js
> +const fetchCommentsByArticle = async (article_id) => {
It's good to stay consistent, either with ```async/await``` or ```.then```  throughout, so I'd encourage you to keep one or the other for the sake of consistency in your portfolio piece :)

2023-08-17 08:10 UTC, mezzDavies approved these changes
Approved but I have left a comment as a strong recommendation 👍 

(Don't for get to name the branch after task next time round! 😄 )

2023-08-17 08:10 UTC, mezzDavies commented on models/topic-model.js
> +    .then(articleExistsResult => {
I would have a look at [these notes](https://notes.northcoders.com/courses/js-back-end/advanced-error-handling) about how to implement this checkExists and make it reusable 👍

2023-08-17 08:13 UTC, merged